name: Format Codes

on:
  push:
    paths:
    - "**.py"
    - "**.yml"
  workflow_dispatch:

jobs:
  Format_Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"
      - name: Install Formatting Tools
        run: pip install autopep8 autoflake isort black
      - name: Run autopep8
        run: |
          autopep8 --verbose --in-place --recursive --aggressive *.py
      - name: Clean Imports
        run: |
          isort .
          autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .
      - name: Format
        run: |
          black .
          isort .

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "Format Codes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: "github-actions[bot]"
            commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
