name: Pre Commit

on:
  push:
    paths:
      - "**/*.py"
      - "**.yml"
  workflow_dispatch:

jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install Pre-commit
        run: pip install pre-commit
      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Code Formatting Fixes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          
